version: '3.0'

services:
  rollup:
    build: .
    volumes:
      - .:/campo-ui
    command: npx rollup --config --watch
  hexo:
    build: .
    volumes:
      - .:/campo-ui
    command: npx hexo server
    ports:
      - 4000:4000
