version: '3.0'

services:
  web:
    build: .
    volumes:
      - .:/app
    command: npx hexo server
    ports:
      - 4000:4000
  build-js:
    build: .
    volumes:
      - .:/app
    command: npm run build:js-bundle -- --watch
    tty: true
  build-css:
    build: .
    volumes:
      - .:/app
    command: npm run build:css -- --watch
