version: '3.0'

services:
  webpack:
    build: .
    volumes:
      - .:/campo-ui
    command: npx webpack-dev-server --host 0.0.0.0
    environment:
      NODE_ENV: development
    ports:
      - 8080:8080
  hexo:
    build: .
    volumes:
      - .:/campo-ui
    command: npx hexo generate --watch
