name: GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build_and_publish:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm install
      - run: npx hexo generate
      - run: npm run build
      - name: Publish to GitHub Pages
        run: |
          cd dist
          touch .nojekyll
          git init
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add .
          git commit -m 'update site'
          git push --force https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git master:gh-pages
          rm -fr .git
          cd ..
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
